# Generated by Django 3.2.6 on 2021-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
