# Generated by Django 3.2.6 on 2021-08-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0005_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
