# Generated by Django 3.2.6 on 2021-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0006_auto_20210826_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
