# Generated by Django 3.2.6 on 2021-08-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0008_alter_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
