# Generated by Django 3.2.6 on 2021-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0010_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
