# Generated by Django 3.2.6 on 2021-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0015_alter_lesson_lesson_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_number',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lessonID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
