# Generated by Django 3.2.6 on 2021-11-12 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0016_auto_20211111_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessonID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
