# Generated by Django 3.2.6 on 2021-11-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0017_alter_lesson_lessonid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessonID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
