# Generated by Django 3.2.6 on 2021-11-23 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplanner', '0018_alter_lesson_lessonid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessonID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
